### ISSUE TITLE
FeatureRequest: placeholder appending

### ISSUE THREAD

**Issue by phux** [martinohmann/kickoff#42]
To be able to use `kickoff` for in-project features (not a new project, but just a set of files), it would be handy to be able to define placeholders, for example in config files.

Example use case:
Given that I have a config file, if I want to bootstrap a set of files, and one of them needs to be included in a config file, it's right now not possible.
If I could define a placeholder in the config file that `kickoff` interprets as `don't replace, make sure all values of a list are there`, `kickoff could be also used for feature creation.

Example file:
```yaml
# config/services.yaml
imports:
    # kickoff:block:<my_identifier>:start
    - { resource: services/kickoff_created_config1.yaml }
    - { resource: services/kickoff_created_config2.yaml }
    # kickoff:block:<my_identifier>:end
```
By placing an `end` marker automatically after the inserted values, `kickoff` would know what block to append on consecutive runs.

**Comment by martinohmann** [comment]
Hey, I'm wondering where the inserted values are coming from. Are these coming from newly added files? Also I'm not sure how kickoff should detect what to append to the block. It's probably also hard to detect whether something was already added or not.

In general it's rather complicated and error-prone to handle files that are both manipulated by a human and a machine.

I just recently merged two features which make it possible to do something similar:
* https://github.com/martinohmann/kickoff/pull/44
* https://github.com/martinohmann/kickoff/pull/43

Given you have a file `config.yaml.skel` with this content:

```yaml
imports:
{{ .Values.imports | toYAML }}
```

And then you have a `values.yaml` file which is not part of the skeleton but which you pass to `kickoff project create` via `--values` which looks like this:

```yaml
imports:
- resource: services/config1.yaml
- resource: services/config2.yaml
```
Whenever you add a new service, you'd add it to the `values.yaml` and rerun `kickoff project create` with the `--overwrite` flag.

```bash
kickoff project create myskeleton ~/myproject --overwrite --force --values values.yaml
```

The only thing I see missing here is to add functionality that lets you only selectively overwrite existing project files (e.g. a flag `--overwrite-file <file>` which you can specify multiple times). Because right now `--overwrite` would overwrite all project files with files from the skeleton that have the same name.

Would that be an option for you to solve this problem?
